In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("List_of_Jobs_to_Apply.csv")
df

,Job Title,Company,Location,Salary($),Job-Type,Job-Description,Raw_Link
0,AI Content Writer,DataAnnotation,Remote,$20 - $25 an hour,Contract,You will have conversations with chatbots in o...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...
1,AI Focused Biochemistry Postdoctoral Fellow,Lawrence Berkeley National Laboratory,"San Francisco Bay Area, CA","$77,172 - $103,704 a year",Not Provided,Berkeley Lab’s Applied Mathematics and Computa...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...
2,MRI Technologist,Lenox Hill Radiology,"Freeport, NY 11520",$40 - $60 an hour,Part-time,Perform high quality MRI exams on incoming pat...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...
3,AI Content Writer (Tier 1),Outlier Ai,California,Not Provided,Not Provided,Flexible work schedule: Work whenever and wher...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...
4,Google Cloud Platform Data Engineer,Publicis Sapient,"Houston, TX","$115,000 - $150,000 a year",Full-time,This position requires in-depth knowledge and ...,https://www.indeed.com/pagead/clk?mo=r&ad=-6NY...
...,...,...,...,...,...,...,...
14997,Competitive Intelligence Lead,"Grammarly, Inc.",Hybrid work in United States,Not Provided,Not Provided,Has experience working at a senior level in co...,https://www.indeed.com/rc/clk?jk=416f3bf573d88...
14998,"Senior Writer and Editor, AI at Work",Microsoft,United States,"$103,800 - $219,200 a year",Full-time,The writer and editor will also contribute reg...,https://www.indeed.com/rc/clk?jk=a753f4b4e9424...
14999,AI Data Annotator,Vistatec,United States,Not Provided,Not Provided,Data Annotators carry out their work in an eng...,https://www.indeed.com/rc/clk?jk=644269f566114...
15000,Sustainability Go-to-Market Activation Lead,Microsoft,United States,"$129,200 - $268,900 a year",Full-time,Sitting in the Cross Solutions Sales Activatio...,https://www.indeed.com/rc/clk?jk=da0e0b51bf349...
15001,Partner Technology Strategy AI Services,Microsoft,United States,"$103,800 - $219,200 a year",Full-time,"As a Partner Technology Strategist, you will d...",https://www.indeed.com/rc/clk?jk=2f0cd40c3bb39...

In [5]:
num_duplicates = df.duplicated().sum()
print(f"Number of duplicate rows: {num_duplicates}")

Number of duplicate rows: 0